FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json  ./

COPY apps ./apps
COPY packages ./packages

RUN npm install
RUN cd apps/web && npx prisma generate && cd ../..

RUN npm run build

CMD ["npm", "run", "start-user-app"] 